#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Hook-LexWrap
Version  : 0.26
Release  : 12
URL      : https://cpan.metacpan.org/authors/id/E/ET/ETHER/Hook-LexWrap-0.26.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/E/ET/ETHER/Hook-LexWrap-0.26.tar.gz
Summary  : 'Lexically scoped subroutine wrappers'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Hook-LexWrap-license = %{version}-%{release}
Requires: perl-Hook-LexWrap-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
This archive contains the distribution Hook-LexWrap,
version 0.26:
Lexically scoped subroutine wrappers

%package dev
Summary: dev components for the perl-Hook-LexWrap package.
Group: Development
Provides: perl-Hook-LexWrap-devel = %{version}-%{release}
Requires: perl-Hook-LexWrap = %{version}-%{release}

%description dev
dev components for the perl-Hook-LexWrap package.


%package license
Summary: license components for the perl-Hook-LexWrap package.
Group: Default

%description license
license components for the perl-Hook-LexWrap package.


%package perl
Summary: perl components for the perl-Hook-LexWrap package.
Group: Default
Requires: perl-Hook-LexWrap = %{version}-%{release}

%description perl
perl components for the perl-Hook-LexWrap package.


%prep
%setup -q -n Hook-LexWrap-0.26
cd %{_builddir}/Hook-LexWrap-0.26

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Hook-LexWrap
cp %{_builddir}/Hook-LexWrap-0.26/LICENSE %{buildroot}/usr/share/package-licenses/perl-Hook-LexWrap/7cb8c947e63b7e34037d3e59d10f3584f3fe355d
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Hook::LexWrap.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Hook-LexWrap/7cb8c947e63b7e34037d3e59d10f3584f3fe355d

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
